#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Spotify desktop='^4'
bspc rule -a "Firefox Developer Edition" desktop='^3'
#bspc rule -a "Google Chrome Dev" desktop='^2'
#bspc rule -a "Google Chrome Unstable" desktop='^2'
bspc rule -a "Google-chrome-unstable" desktop='^4'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

