#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding        15 
bspc config bottom_padding     15
bspc config left_padding       11
bspc config right_padding      11

bspc config border_width        4
bspc config window_gap          8


# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a "Mullvad VPN" desktop='^1' state=floating
#bspc rule -a Chromium desktop='^2' follow=on focus=on
#bspc rule -a "Firefox Developer Edition" desktop='^3' follow=on focus=on
#bspc rule -a "Google Chrome Dev" desktop='^2'
#bspc rule -a "Google Chrome Unstable" desktop='^2'
#bspc rule -a "Google-chrome-unstable" desktop='^4' follow=on focus=on
#bspc rule -a feh floating=on manage=off
bspc rule -a feh state=floating=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#mullvad-vpn&

